<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="2" passed="1">
  <reporter-output>
    <line>
      <![CDATA[open the appl]]>
    </line>
    <line>
      <![CDATA[bye]]>
    </line>
    <line>
      <![CDATA[faliur]]>
    </line>
    <line>
      <![CDATA[open the appl]]>
    </line>
    <line>
      <![CDATA[hello]]>
    </line>
  </reporter-output>
  <suite name="Default suite" duration-ms="58" started-at="2018-09-04T03:37:26Z" finished-at="2018-09-04T03:37:26Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="58" started-at="2018-09-04T03:37:26Z" finished-at="2018-09-04T03:37:26Z">
      <class name="Qp.Abc">
        <test-method status="FAIL" signature="closezpp()[pri:0, instance:Qp.Abc@6fd02e5]" name="closezpp" duration-ms="17" started-at="2018-09-04T09:07:26Z" finished-at="2018-09-04T09:07:26Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.fail(Assert.java:101)
	at Qp.Abc.closezpp(Abc.java:20)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[bye]]>
            </line>
            <line>
              <![CDATA[faliur]]>
            </line>
          </reporter-output>
        </test-method> <!-- closezpp -->
        <test-method status="PASS" signature="openzpp()[pri:0, instance:Qp.Abc@6fd02e5]" name="openzpp" duration-ms="8" started-at="2018-09-04T09:07:26Z" finished-at="2018-09-04T09:07:26Z">
          <reporter-output>
            <line>
              <![CDATA[hello]]>
            </line>
          </reporter-output>
        </test-method> <!-- openzpp -->
      </class> <!-- Qp.Abc -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
